from __future__ import annotations

from dataclasses import dataclass

from kleptography.crypto.dh.validation import validate_parameters
from kleptography.math.primes import (
    generate_safe_prime,
    generate_subgroup_generator,
)


@dataclass(frozen=True, slots=True)
class DiffieHellmanParameters:
    """
    Parameters defining a finite-field Diffie-Hellman group.

    Attributes:
        prime: The prime modulus p.
        generator: A generator of the subgroup used by DH.
        subgroup_order: The order q of the subgroup generated by `generator`.

    The parameters can either come from a standardized group or be generated
    as deliberately insecure educational parameters.
    """

    prime: int
    generator: int
    subgroup_order: int

    def __post_init__(self) -> None:
        """Validate the mathematical invariants of the DH parameters."""
        validate_parameters(
            prime=self.prime,
            generator=self.generator,
            subgroup_order=self.subgroup_order,
        )

    @property
    def bit_length(self) -> int:
        """Return the bit length of the prime modulus."""
        return self.prime.bit_length()

    @property
    def byte_length(self) -> int:
        """Return the number of bytes needed to encode any value modulo p."""
        return (self.prime.bit_length() + 7) // 8

    @classmethod
    def generate_toy(cls, bits: int = 32) -> "DiffieHellmanParameters":
        """
        Generate deliberately insecure DH parameters for educational use.

        The modulus is a safe prime:

            p = 2q + 1

        where both p and q are prime.

        The generator has exactly order q.

        This method is intended exclusively for demonstrations and tests.
        The resulting parameters must never be used for real cryptography.
        """
        prime = generate_safe_prime(bits)
        subgroup_order = (prime - 1) // 2
        generator = generate_subgroup_generator(prime)

        return cls(
            prime=prime,
            generator=generator,
            subgroup_order=subgroup_order,
        )

    @classmethod
    def from_standard(
        cls,
        *,
        prime: int,
        generator: int,
        subgroup_order: int,
    ) -> "DiffieHellmanParameters":
        """
        Construct parameters from a standardized DH group.

        The caller is responsible for providing parameters from a trusted
        standard or other authoritative specification.
        """
        return cls(
            prime=prime,
            generator=generator,
            subgroup_order=subgroup_order,
        )
